# Generated by Django 2.2.10 on 2020-07-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'ordering': ('-list_date',)},
        ),
        migrations.AlterField(
            model_name='listings',
            name='list_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
