# Generated by Django 2.2.10 on 2020-07-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200707_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='bal',
            field=models.BooleanField(default=False),
        ),
    ]
