# Generated by Django 2.2.10 on 2020-07-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtos', '0003_auto_20200707_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='mvp_is',
        ),
    ]
