# Generated by Django 2.2.10 on 2020-07-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtos', '0004_remove_realtor_mvp_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
    ]
